
import type { MediaType, GenreType, FandomPost } from './types';
import { placeholderImages } from './placeholder-images.json';

const findImage = (id: string) => {
  const img = placeholderImages.find((p) => p.id === id);
  return {
    url: img?.imageUrl || 'https://picsum.photos/seed/placeholder/300/450',
    hint: img?.imageHint || 'placeholder',
  };
};

export const media: MediaType[] = [
  {
    id: 'cyber-sentinel',
    title: 'Cyber Sentinel',
    type: 'Anime',
    description: 'In a neon-drenched future, a lone android fights to protect humanity.',
    longDescription: 'In the year 2077, Neo-Kyoto is a sprawling metropolis of towering skyscrapers and shadowy alleys. Kaito, a state-of-the-art android known as a "Sentinel," uncovers a corporate conspiracy that threatens the very fabric of society. He must fight his way through rogue machines and augmented humans to expose the truth.',
    genres: ['Sci-Fi', 'Action', 'Cyberpunk'],
    rating: 4.8,
    imageUrl: findImage('anime-1').url,
    imageHint: findImage('anime-1').hint,
    status: 'Featured',
    duration: '24 min per ep',
    releaseYear: 2023,
  },
  {
    id: 'chainsaw-man-reze-arc',
    title: 'Chainsaw Man: The Movie - Reze Arc',
    type: 'Anime',
    description: 'Denji falls for a new girl, Reze, who is not what she seems.',
    longDescription: 'Denji meets Reze, a girl who is seemingly his perfect match. But their budding romance is tragically cut short when it is revealed that Reze is the Bomb Devil, sent to steal the Chainsaw Man\'s heart. A heart-wrenching battle ensues, testing Denji\'s resolve and his very humanity.',
    genres: ['Action', 'Supernatural', 'Horror'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/chainsaw-man-the-movie-reze-arc-1-285x399.webp?t=1750358534',
    imageHint: 'chainsaw man reze',
    status: 'Trending',
    duration: '1h 30min',
    releaseYear: 2025,
  },
  {
    id: 'the-apothecary-diaries-2nd-season',
    title: 'The Apothecary Diaries 2nd Season',
    type: 'Anime',
    description: 'Maomao solves more medical mysteries in the imperial court.',
    longDescription: 'The clever and cynical Maomao continues her life as a palace apothecary. With her extensive knowledge of medicine and poisons, she once again finds herself entangled in the complex and often dangerous affairs of the imperial inner court, solving medical mysteries that baffle everyone else.',
    genres: ['Mystery', 'Historical', 'Drama'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-apothecary-diaries-2nd-season-1-285x403.webp?t=1729603194',
    imageHint: 'apothecary maomao',
    status: 'Trending',
    duration: '24 min per ep',
    releaseYear: 2025,
  },
  {
    id: 'death-stranding-isolation',
    title: 'Death Stranding: Isolation',
    type: 'Anime',
    description: 'In a world fractured by the Death Stranding, a lone porter uncovers a new mystery.',
    longDescription: 'In a world fractured by the Death Stranding, a lone porter uncovers a new mystery that threatens the fragile connections of a rebuilt society. This new chapter explores the isolated corners of the devastated landscape and the lonely souls who inhabit it.',
    genres: ['Sci-Fi', 'Mystery', 'Adventure'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/death-stranding-isolation-1-285x398.webp?t=1763258880',
    imageHint: 'porter isolation',
    status: 'Latest',
    duration: 'TBA',
    releaseYear: 2026,
  },
  {
    id: 'may-i-ask-for-one-final-thing',
    title: 'May I Ask For One Final Thing?',
    type: 'Anime',
    description: 'A scorned noblewoman unleashes her fury upon those who betrayed her.',
    longDescription: 'Scarlett, a noblewoman whose engagement was suddenly annulled, is falsely accused and thrown into prison. When she\'s pushed to her limit, she decides to stop holding back. "May I ask for one final thing?" she says, before unleashing her true, violent nature upon her tormentors. This is a story of brutal, satisfying revenge.',
    genres: ['Action', 'Fantasy', 'Romance'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/may-i-ask-for-one-final-thing-1-285x427.webp?t=1744408497',
    imageHint: 'furious noblewoman',
    status: 'Trending',
    duration: '24 min per ep',
    releaseYear: 2024,
  },
  {
    id: 'the-most-heretical-last-boss-queen',
    title: 'The Most Heretical Last Boss Queen: From Villainess to Savior',
    type: 'Anime',
    description: 'A reincarnated villainess uses her powers to save her kingdom.',
    longDescription: 'Pride Royal Ivy is only eight years old when she realizes that she has been reincarnated, destined to become the future wicked queen and final boss of an otome game. She has everything from her past life’s game: wit, boss-level abilities, and influence over the kingdom. Now, she’s determined to use her powers to save her father, the kingdom, and everyone in her path!',
    genres: ['Fantasy', 'Isekai', 'Romance'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-most-heretical-last-boss-queen-from-villainess-to-savior-1-285x399.webp?t=1682499892',
    imageHint: 'villainess queen',
    status: 'Latest',
    duration: '24 min per ep',
    releaseYear: 2023,
  },
  {
    id: 'the-banished-court-magician-aims-to-become-the-strongest',
    title: 'The Banished Court Magician Aims to Become the Strongest',
    type: 'Anime',
    description: 'A talented magician, banished from court, seeks to become the strongest of all.',
    longDescription: 'Betrayed and exiled from the royal court he served, a prodigious magician now wanders the lands. To protect those he cares for and to prove his worth, he embarks on a solitary journey to hone his skills and surpass every magical limit, aiming to become the undisputed strongest magician in the world.',
    genres: ['Fantasy', 'Adventure', 'Action'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-banished-court-magician-aims-to-become-the-strongest-1-285x399.webp?t=1759618348',
    imageHint: 'court magician',
    status: 'Trending',
    duration: '24 min per ep',
    releaseYear: 2025,
  },
  {
    id: 'i-became-a-patron-of-villains',
    title: 'I Became a Patron of Villains',
    type: 'Manga',
    description: 'A woman is reincarnated into a novel to become a patron for the villains she once pitied.',
    longDescription: 'Waking up in the world of her favorite novel, a character decides she\'s had enough of the tragic fates of its villains. Instead of following the plot, she uses her knowledge to become their secret supporter, guiding them away from their dark destinies while trying to survive in a world where her actions could have unforeseen consequences.',
    genres: ['Fantasy', 'Isekai', 'Drama'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/i-became-a-patron-of-villains-1-285x399.webp?t=1761280414',
    imageHint: 'patron of villains',
    status: 'Trending',
    chapters: 80,
    releaseYear: 2022,
  },
  {
    id: 'chainsaw-man',
    title: 'Chainsaw Man',
    type: 'Manga',
    description: 'A destitute boy makes a deal with a devil to become a devil hunter.',
    longDescription: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil-dog Pochita and becomes a new man—a man with a devil’s heart and the powers of a chainsaw. Now he’s living in the big city and an official Devil Hunter, but he\'s got a lot to learn about his new job and chainsaw powers.',
    genres: ['Action', 'Supernatural', 'Horror'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/chainsaw-man-1-285x428.jpg?t=1634713911',
    imageHint: 'chainsaw devil',
    status: 'Trending',
    chapters: 150,
    releaseYear: 2018,
  },
  {
    id: 'birinnae',
    title: 'Birinnae',
    type: 'Manga',
    description: 'In a world of myth and legend, a young woman discovers a power that could save or destroy the kingdom.',
    longDescription: 'In a world of myth and legend, a young woman named Birinnae discovers she holds a power that could either save or destroy the kingdom. Chased by those who want to control her, she must uncover the secrets of her past to forge her own destiny.',
    genres: ['Fantasy', 'Adventure', 'Drama'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/birinnae-1-285x399.webp?t=1762904250',
    imageHint: 'fantasy girl',
    status: 'Trending',
    chapters: 50,
    releaseYear: 2023,
  },
   {
    id: 'ore-no-ojuken',
    title: 'Ore no Ojuken',
    type: 'Manga',
    description: 'A father\'s hilarious and heartfelt journey into the world of middle school entrance exams.',
    longDescription: 'When his beloved daughter decides to take on the notoriously difficult middle school entrance exams, a former delinquent father dives headfirst into the world of cram schools, mock tests, and helicopter parents. A hilarious and heartfelt story about family bonds and the lengths a parent will go to for their child.',
    genres: ['Comedy', 'Slice of Life', 'Drama'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/ore-no-ojuken-1-285x399.webp?t=1762848333',
    imageHint: 'exam father',
    status: 'Trending',
    chapters: 20,
    releaseYear: 2021,
  },
  {
    id: 'ill-become-a-villainess-who-goes-down-in-history',
    title: 'I\'ll Become a Villainess Who Goes Down in History',
    type: 'Anime',
    description: 'A girl reincarnated as a villainess decides to become the worst one ever.',
    longDescription: 'Alicia realizes she has been reborn as the villainess in an otome game. Instead of avoiding her bad ending, she decides to embrace it and become the most wicked villainess in history, aiming for a fate so grandly evil it will be remembered forever. She will outsmart the heroine and all the capture targets!',
    genres: ['Fantasy', 'Isekai', 'Comedy'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/ill-become-a-villainess-who-goes-down-in-history-1-285x399.webp?t=1734746036',
    imageHint: 'smirking villainess',
    status: 'Latest',
    duration: '24 min per ep',
    releaseYear: 2024,
  },
  {
    id: 'absolute-regression',
    title: 'Absolute Regression',
    type: 'Manga',
    description: 'To save the world, he must relive his past and become stronger than ever before.',
    longDescription: 'After the world is destroyed, a powerful warrior is given a second chance, regressing to his younger self. With his knowledge of the future, he trains to master his abilities and change the course of history, facing old enemies and new threats along the way.',
    genres: ['Action', 'Fantasy', 'Adventure'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/absolute-regression-1-285x399.webp?t=1749598184',
    imageHint: 'warrior regression',
    status: 'Latest',
    chapters: 120,
    releaseYear: 2023,
  },
];

export const genres: GenreType[] = [
  {
    id: 'action',
    name: 'Action',
    description: 'High-octane series with intense fight scenes and thrilling sequences.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452301/lgi39qi7kmzdipemivm1_p9kewu.jpg',
    imageHint: 'action explosion',
  },
  {
    id: 'romance',
    name: 'Romance',
    description: 'Heartwarming stories centered around love and relationships.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452574/blue-box-and-horimiya_hxxsuo.avif',
    imageHint: 'romantic couple',
  },
  {
    id: 'sci-fi',
    name: 'Sci-Fi',
    description: 'Futuristic settings, advanced technology, and space exploration.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452482/Sci-fi-anime_qp7ers.webp',
    imageHint: 'sci-fi city',
  },
  {
    id: 'fantasy',
    name: 'Fantasy',
    description: 'Worlds of magic, mythical creatures, and epic quests.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452812/desktop-wallpaper-anime-boy-under-umbrella-with-black-coat-suit-dress-anime-boy_tw8cdi.jpg',
    imageHint: 'fantasy castle',
  },
  {
    id: 'comedy',
    name: 'Comedy',
    description: 'Lighthearted series designed to make you laugh.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1763280262/comedy-anime-series-ott_bhzgc1.jpg',
    imageHint: 'funny characters',
  },
  {
    id: 'drama',
    name: 'Drama',
    description: 'Emotionally charged narratives and character development.',
    imageUrl: findImage('genre-drama').url,
    imageHint: findImage('genre-drama').hint,
  },
];

export const fandomPosts: FandomPost[] = [
  {
    id: 1,
    author: 'AnimeFan_123',
    avatarUrl: findImage('avatar-1').url,
    avatarHint: findImage('avatar-1').hint,
    content: "Just finished Cyber Sentinel. The ending was absolutely mind-blowing! I can't believe they pulled that off. 10/10 masterpiece.",
    timestamp: '2 hours ago',
    sentiment: 'positive',
    sentimentScore: 0.9,
  },
  {
    id: 2,
    author: 'MechaMaster',
    avatarUrl: findImage('avatar-2').url,
    avatarHint: findImage('avatar-2').hint,
    content: 'The new episode of Iron-Clad Dynasty was okay, but the animation felt a bit off in the main fight scene. Anyone else notice that?',
    timestamp: '5 hours ago',
    sentiment: 'neutral',
    sentimentScore: -0.2,
  },
  {
    id: 3,
    author: 'ShojoLover',
    avatarUrl: findImage('avatar-3').url,
    avatarHint: findImage('avatar-3').hint,
    content: 'I really hated how they handled the main couple in Rooftop Confessions. It felt so forced and unnatural. Ruined the whole series for me.',
    timestamp: '1 day ago',
    sentiment: 'negative',
    sentimentScore: -0.8,
  },
];
