
import type { MediaType, GenreType, FandomPost } from './types';
import { placeholderImages } from './placeholder-images.json';

const findImage = (id: string) => {
  const img = placeholderImages.find((p) => p.id === id);
  return {
    url: img?.imageUrl || 'https://picsum.photos/seed/placeholder/300/450',
    hint: img?.imageHint || 'placeholder',
  };
};

export const media: MediaType[] = [
  {
    id: 'cyber-sentinel',
    title: 'Cyber Sentinel',
    type: 'Anime',
    description: 'In a neon-drenched future, a lone android fights to protect humanity.',
    longDescription: 'In the year 2077, Neo-Kyoto is a sprawling metropolis of towering skyscrapers and shadowy alleys. Kaito, a state-of-the-art android known as a "Sentinel," uncovers a corporate conspiracy that threatens the very fabric of society. He must fight his way through rogue machines and augmented humans to expose the truth.',
    genres: ['Sci-Fi', 'Action', 'Cyberpunk'],
    rating: 4.8,
    imageUrl: findImage('anime-1').url,
    imageHint: findImage('anime-1').hint,
    status: 'Featured',
    duration: '24 min per ep',
    releaseYear: 2023,
  },
  {
    id: 'chainsaw-man-reze-arc',
    title: 'Chainsaw Man: The Movie - Reze Arc',
    type: 'Anime',
    description: 'Denji falls for a new girl, Reze, who is not what she seems.',
    longDescription: 'Denji meets Reze, a girl who is seemingly his perfect match. But their budding romance is tragically cut short when it is revealed that Reze is the Bomb Devil, sent to steal the Chainsaw Man\'s heart. A heart-wrenching battle ensues, testing Denji\'s resolve and his very humanity.',
    genres: ['Action', 'Supernatural', 'Horror'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/chainsaw-man-the-movie-reze-arc-1-285x399.webp?t=1750358534',
    imageHint: 'chainsaw man reze',
    status: 'Trending',
    duration: '1h 30min',
    releaseYear: 2025,
  },
  {
    id: 'the-apothecary-diaries-2nd-season',
    title: 'The Apothecary Diaries 2nd Season',
    type: 'Anime',
    description: 'Maomao solves more medical mysteries in the imperial court.',
    longDescription: 'The clever and cynical Maomao continues her life as a palace apothecary. With her extensive knowledge of medicine and poisons, she once again finds herself entangled in the complex and often dangerous affairs of the imperial inner court, solving medical mysteries that baffle everyone else.',
    genres: ['Mystery', 'Historical', 'Drama'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-apothecary-diaries-2nd-season-1-285x403.webp?t=1729603194',
    imageHint: 'apothecary maomao',
    status: 'Trending',
    duration: '24 min per ep',
    releaseYear: 2025,
  },
  {
    id: 'death-stranding-isolation',
    title: 'Death Stranding: Isolation',
    type: 'Anime',
    description: 'In a world fractured by the Death Stranding, a lone porter uncovers a new mystery.',
    longDescription: 'In a world fractured by the Death Stranding, a lone porter uncovers a new mystery that threatens the fragile connections of a rebuilt society. This new chapter explores the isolated corners of the devastated landscape and the lonely souls who inhabit it.',
    genres: ['Sci-Fi', 'Mystery', 'Adventure'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/death-stranding-isolation-1-285x398.webp?t=1763258880',
    imageHint: 'porter isolation',
    status: 'Latest',
    duration: 'TBA',
    releaseYear: 2026,
  },
  {
    id: 'may-i-ask-for-one-final-thing',
    title: 'May I Ask For One Final Thing?',
    type: 'Anime',
    description: 'A scorned noblewoman unleashes her fury upon those who betrayed her.',
    longDescription: 'Scarlett, a noblewoman whose engagement was suddenly annulled, is falsely accused and thrown into prison. When she\'s pushed to her limit, she decides to stop holding back. "May I ask for one final thing?" she says, before unleashing her true, violent nature upon her tormentors. This is a story of brutal, satisfying revenge.',
    genres: ['Action', 'Fantasy', 'Romance'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/may-i-ask-for-one-final-thing-1-285x427.webp?t=1744408497',
    imageHint: 'furious noblewoman',
    status: 'Trending',
    duration: '24 min per ep',
    releaseYear: 2024,
  },
  {
    id: 'the-most-heretical-last-boss-queen',
    title: 'The Most Heretical Last Boss Queen: From Villainess to Savior',
    type: 'Anime',
    description: 'A reincarnated villainess uses her powers to save her kingdom.',
    longDescription: 'Pride Royal Ivy is only eight years old when she realizes that she has been reincarnated, destined to become the future wicked queen and final boss of an otome game. She has everything from her past life’s game: wit, boss-level abilities, and influence over the kingdom. Now, she’s determined to use her powers to save her father, the kingdom, and everyone in her path!',
    genres: ['Fantasy', 'Isekai', 'Romance'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-most-heretical-last-boss-queen-from-villainess-to-savior-1-285x399.webp?t=1682499892',
    imageHint: 'villainess queen',
    status: 'Latest',
    duration: '24 min per ep',
    releaseYear: 2023,
  },
  {
    id: 'the-banished-court-magician-aims-to-become-the-strongest',
    title: 'The Banished Court Magician Aims to Become the Strongest',
    type: 'Anime',
    description: 'A talented magician, banished from court, seeks to become the strongest of all.',
    longDescription: 'Betrayed and exiled from the royal court he served, a prodigious magician now wanders the lands. To protect those he cares for and to prove his worth, he embarks on a solitary journey to hone his skills and surpass every magical limit, aiming to become the undisputed strongest magician in the world.',
    genres: ['Fantasy', 'Adventure', 'Action'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-banished-court-magician-aims-to-become-the-strongest-1-285x399.webp?t=1759618348',
    imageHint: 'court magician',
    status: 'Trending',
    duration: '24 min per ep',
    releaseYear: 2025,
  },
  {
    id: 'i-became-a-patron-of-villains',
    title: 'I Became a Patron of Villains',
    type: 'Manga',
    description: 'A woman is reincarnated into a novel to become a patron for the villains she once pitied.',
    longDescription: 'Waking up in the world of her favorite novel, a character decides she\'s had enough of the tragic fates of its villains. Instead of following the plot, she uses her knowledge to become their secret supporter, guiding them away from their dark destinies while trying to survive in a world where her actions could have unforeseen consequences.',
    genres: ['Fantasy', 'Isekai', 'Drama'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/i-became-a-patron-of-villains-1-285x399.webp?t=1761280414',
    imageHint: 'patron of villains',
    status: 'Trending',
    chapters: 80,
    releaseYear: 2022,
  },
  {
    id: 'chainsaw-man',
    title: 'Chainsaw Man',
    type: 'Manga',
    description: 'A destitute boy makes a deal with a devil to become a devil hunter.',
    longDescription: 'Denji was a small-time devil hunter just trying to survive in a harsh world. After being killed on a job, he is revived by his pet devil-dog Pochita and becomes a new man—a man with a devil’s heart and the powers of a chainsaw. Now he’s living in the big city and an official Devil Hunter, but he\'s got a lot to learn about his new job and chainsaw powers.',
    genres: ['Action', 'Supernatural', 'Horror'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/chainsaw-man-1-285x428.jpg?t=1634713911',
    imageHint: 'chainsaw devil',
    status: 'Trending',
    chapters: 150,
    releaseYear: 2018,
  },
  {
    id: 'birinnae',
    title: 'Birinnae',
    type: 'Manga',
    description: 'In a world of myth and legend, a young woman discovers a power that could save or destroy the kingdom.',
    longDescription: 'In a world of myth and legend, a young woman named Birinnae discovers she holds a power that could either save or destroy the kingdom. Chased by those who want to control her, she must uncover the secrets of her past to forge her own destiny.',
    genres: ['Fantasy', 'Adventure', 'Drama'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/birinnae-1-285x399.webp?t=1762904250',
    imageHint: 'fantasy girl',
    status: 'Trending',
    chapters: 50,
    releaseYear: 2023,
  },
   {
    id: 'ore-no-ojuken',
    title: 'Ore no Ojuken',
    type: 'Manga',
    description: 'A father\'s hilarious and heartfelt journey into the world of middle school entrance exams.',
    longDescription: 'When his beloved daughter decides to take on the notoriously difficult middle school entrance exams, a former delinquent father dives headfirst into the world of cram schools, mock tests, and helicopter parents. A hilarious and heartfelt story about family bonds and the lengths a parent will go to for their child.',
    genres: ['Comedy', 'Slice of Life', 'Drama'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/ore-no-ojuken-1-285x399.webp?t=1762848333',
    imageHint: 'exam father',
    status: 'Trending',
    chapters: 20,
    releaseYear: 2021,
  },
  {
    id: 'ill-become-a-villainess-who-goes-down-in-history',
    title: 'I\'ll Become a Villainess Who Goes Down in History',
    type: 'Anime',
    description: 'A girl reincarnated as a villainess decides to become the worst one ever.',
    longDescription: 'Alicia realizes she has been reborn as the villainess in an otome game. Instead of avoiding her bad ending, she decides to embrace it and become the most wicked villainess in history, aiming for a fate so grandly evil it will be remembered forever. She will outsmart the heroine and all the capture targets!',
    genres: ['Fantasy', 'Isekai', 'Comedy'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/ill-become-a-villainess-who-goes-down-in-history-1-285x399.webp?t=1734746036',
    imageHint: 'smirking villainess',
    status: 'Latest',
    duration: '24 min per ep',
    releaseYear: 2024,
  },
  {
    id: 'absolute-regression',
    title: 'Absolute Regression',
    type: 'Manga',
    description: 'To save the world, he must relive his past and become stronger than ever before.',
    longDescription: 'After the world is destroyed, a powerful warrior is given a second chance, regressing to his younger self. With his knowledge of the future, he trains to master his abilities and change the course of history, facing old enemies and new threats along the way.',
    genres: ['Action', 'Fantasy', 'Adventure'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/absolute-regression-1-285x399.webp?t=1749598184',
    imageHint: 'warrior regression',
    status: 'Latest',
    chapters: 120,
    releaseYear: 2023,
  },
  {
    id: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    type: 'Anime',
    description: 'A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself.',
    longDescription: 'Yuji Itadori, a kind-hearted high school student, joins his school\'s Occult Club for fun, but discovers that its members are actual sorcerers who can manipulate the energy between beings for their own use. He hears about a cursed talisman - the finger of Sukuna, a demon - and its location, and decides to retrieve it. But when his friends are attacked by cursed spirits, Yuji swallows the finger to protect them, and becomes cursed himself.',
    genres: ['Action', 'Supernatural', 'Horror'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/jujutsu-kaisen-1-190x286.jpg?t=1625907951',
    imageHint: 'sorcerer curse',
    status: 'Trending',
    duration: '24 min per ep',
    releaseYear: 2020,
  },
  {
    id: 'berserk',
    title: 'Berserk',
    type: 'Manga',
    description: 'A lone warrior battles demons and his own inner darkness.',
    longDescription: 'Guts, a former mercenary now known as the "Black Swordsman," is out for revenge. After a traumatic betrayal, he is cursed to be endlessly pursued by demonic beings. With a gigantic sword and a prosthetic arm, Guts battles his way through a dark medieval world, fighting for his survival and to protect those he loves.',
    genres: ['Dark Fantasy', 'Action', 'Horror'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/berserk-1-285x404.webp?t=1649815138',
    imageHint: 'black swordsman',
    status: 'Trending',
    chapters: 375,
    releaseYear: 1989,
  },
  {
    id: 'vagabond',
    title: 'Vagabond',
    type: 'Manga',
    description: 'The journey of legendary swordsman Miyamoto Musashi.',
    longDescription: 'Based on the novel "Musashi" by Eiji Yoshikawa, this manga follows the life of Shinmen Takezo, who would later become the legendary swordsman Miyamoto Musashi. It is a fictionalized account of his journey from a brash young man to a master of the sword, exploring themes of life, death, and the meaning of strength.',
    genres: ['Historical', 'Action', 'Samurai'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/vagabond-1-190x272.jpg?t=1625908170',
    imageHint: 'samurai journey',
    status: 'Trending',
    chapters: 327,
    releaseYear: 1998,
  },
  {
    id: 'one-punch-man',
    title: 'One-Punch Man',
    type: 'Manga',
    description: 'A hero who can defeat any enemy with a single punch faces the existential crisis of being too strong.',
    longDescription: 'Saitama is a hero who only became a hero for fun. After three years of "special" training, he\'s become so strong that he\'s practically invincible. In fact, he\'s too strong—even his mightiest opponents are taken out with a single punch. Now, the great hero Saitama is bored by his supreme power and is always on the lookout for a more challenging opponent.',
    genres: ['Action', 'Comedy', 'Superhero'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/one-punch-man-1-285x428.webp?t=1712768744',
    imageHint: 'superhero comedy',
    status: 'Trending',
    chapters: 200,
    releaseYear: 2012,
  },
  {
    id: 'my-hero-academia',
    title: 'My Hero Academia',
    type: 'Manga',
    description: 'In a world of superheroes, a boy without powers strives to become the greatest hero.',
    longDescription: 'Izuku Midoriya dreams of becoming a hero, but in a world where 80% of the population has superpowers, or "Quirks," he was born without one. His fate changes when he meets his idol, All Might, who passes on his Quirk to him. Now, Izuku must learn to control his new powers and navigate the challenges of U.A. High School, a prestigious academy for training heroes.',
    genres: ['Action', 'Superhero', 'Comedy'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/my-hero-academia-1-190x285.jpg?t=1625897284',
    imageHint: 'superhero school',
    status: 'Trending',
    chapters: 400,
    releaseYear: 2014,
  },
  {
    id: 'spy-x-family',
    title: 'Spy x Family',
    type: 'Manga',
    description: 'A spy, an assassin, and a telepath create a fake family for a mission, with hilarious results.',
    longDescription: 'The master spy "Twilight" must build a fake family to infiltrate an elite private school for a critical mission. He adopts a telepathic daughter and marries a skilled assassin, neither of whom knows the others\' secret identity. They must navigate the challenges of family life while keeping their true natures hidden, leading to a mix of espionage, action, and heartwarming comedy.',
    genres: ['Comedy', 'Action', 'Slice of Life'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/spy-x-family-1-285x427.jpg?t=1634514980',
    imageHint: 'fake family',
    status: 'Trending',
    chapters: 100,
    releaseYear: 2019,
  },
  {
    id: 'kaiju-no-8',
    title: 'Kaiju No. 8',
    type: 'Manga',
    description: 'A man who cleans up after giant monster attacks unexpectedly gains the power to become one.',
    longDescription: 'Kafka Hibino is a 32-year-old man whose job is to clean up the aftermath of battles between the Japan Defense Force and giant monsters known as Kaiju. After a small, talking monster flies into his mouth, he gains the ability to transform into a powerful Kaiju himself. Now, designated "Kaiju No. 8," he must hide his new identity while trying to achieve his lifelong dream of joining the Defense Force.',
    genres: ['Action', 'Sci-Fi', 'Kaiju'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/kaiju-no-8-1-285x428.jpg?t=1628025821',
    imageHint: 'monster transformation',
    status: 'Trending',
    chapters: 90,
    releaseYear: 2020,
  },
  {
    id: 'tokyo-ghoul',
    title: 'Tokyo Ghoul',
    type: 'Manga',
    description: 'A college student is transformed into a half-ghoul after a chance encounter.',
    longDescription: 'Ken Kaneki, a shy, bookish college student, is instantly drawn to Rize Kamishiro, an avid reader like himself. However, Rize is not exactly who she seems, and this unfortunate meeting pushes Kaneki into the dark, violent world of Ghouls, beings who feed on human flesh. After a fateful encounter, Kaneki is turned into the first half-human, half-ghoul hybrid. He must now navigate two worlds, struggling to fit into ghoul society while hiding his new identity from his human friends.',
    genres: ['Dark Fantasy', 'Horror', 'Supernatural'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/tokyo-ghoul-1-285x409.webp?t=1749044729',
    imageHint: 'ghoul student',
    status: 'Trending',
    chapters: 143,
    releaseYear: 2011,
  },
  {
    id: 'happiness',
    title: 'Happiness',
    type: 'Manga',
    description: 'A boy\'s life is turned upside down after he is attacked by a mysterious girl.',
    longDescription: 'Makoto Okazaki is a high school student and the subject of bullying. One night, he decides to steal the money of his tormentor, but is attacked by a mysterious girl. He survives, but his life changes forever as he discovers he has become a vampire.',
    genres: ['Horror', 'Supernatural', 'Drama'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/happiness-shuzo-oshimi-1-285x399.webp?t=1732055874',
    imageHint: 'vampire boy',
    status: 'Latest',
    chapters: 50,
    releaseYear: 2015,
  },
  {
    id: 'parasyte',
    title: 'Parasyte',
    type: 'Manga',
    description: 'A high school student and his right hand become hosts to a parasitic alien.',
    longDescription: 'Shinichi Izumi is a normal high school student whose life changes when a parasitic alien, a "Parasyte," fails to take over his brain and instead burrows into his right hand. The two must learn to coexist while defending themselves from other Parasytes who see Shinichi as a threat.',
    genres: ['Horror', 'Sci-Fi', 'Action', 'Psychological'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/parasyte-1-190x287.jpg?t=1625908134',
    imageHint: 'parasitic alien',
    status: 'Trending',
    chapters: 64,
    releaseYear: 1988,
  },
  {
    id: 'jungle-juice',
    title: 'Jungle Juice',
    type: 'Manga',
    description: 'A college student\'s life is turned upside down when he uses a mysterious bug spray.',
    longDescription: 'Jang Suchan is an extraordinary college student at the top of the social food chain. But underneath the perfect exterior, he\'s hiding a pair of insect wings that suddenly grew when he used a mysterious bug spray called \'Jungle Juice\'. His life crumbles when he bares his wings to the world to save someone\'s life. When all hope seems lost, he stumbles upon a hidden world of insect humans where he may finally find a way to reverse his condition.',
    genres: ['Action', 'Fantasy', 'Supernatural'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/jungle-juice-1-285x409.webp?t=1717463914',
    imageHint: 'insect wings',
    status: 'Latest',
    chapters: 100,
    releaseYear: 2020,
  },
  {
    id: 'layers',
    title: 'Layers',
    type: 'Manga',
    description: 'Two women, a prosthesis maker and a client, are drawn into a complex, psychological drama.',
    longDescription: 'Kasane is a woman who wears a full-body prosthesis. She visits a prosthesis maker named Saho, who lives in seclusion. As Saho works on Kasane\'s new body, their lives become deeply intertwined, blurring the lines between maker and creation, reality and illusion.',
    genres: ['Psychological', 'Drama', 'Horror'],
    rating: 4.5,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/layers-1-190x254.jpg?t=1625911301',
    imageHint: 'psychological drama',
    status: 'Latest',
    chapters: 10,
    releaseYear: 2011,
  },
  {
    id: 'our-sunny-days',
    title: 'Our Sunny Days',
    type: 'Manga',
    description: 'Two high school students find comfort in each other\'s company, sharing their struggles and joys.',
    longDescription: 'Natsu and Aki are two classmates who couldn\'t be more different. Natsu is cheerful and popular, while Aki is quiet and reserved. A chance encounter on the school rooftop leads to an unlikely friendship. As they spend more time together, they discover they have more in common than they thought, and their bond helps them navigate the challenges of adolescence.',
    genres: ['Slice of Life', 'Romance', 'School'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/our-sunny-days-1-285x399.webp?t=1760310780',
    imageHint: 'school romance',
    status: 'Latest',
    chapters: 30,
    releaseYear: 2022,
  },
  {
    id: 'the-hunters-gonna-lay-low-novel',
    title: 'The Hunter\'s Gonna Lay Low (Novel)',
    type: 'Manga',
    description: 'A top-ranked hunter decides to retire, but his peaceful life is constantly interrupted.',
    longDescription: 'After years of being the top hunter, he decides to retire and live a quiet life. However, his reputation precedes him, and he finds that his peaceful days are anything but. From young challengers to old enemies, everyone wants a piece of the legendary hunter. Will he ever find the tranquility he seeks?',
    genres: ['Action', 'Fantasy', 'Comedy'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/the-hunters-gonna-lay-low-novel-1-285x399.webp?t=1742777743',
    imageHint: 'retired hunter',
    status: 'Latest',
    chapters: 60,
    releaseYear: 2023,
  },
  {
    id: 'the-summer-hikaru-died',
    title: 'The Summer Hikaru Died',
    type: 'Manga',
    description: 'A boy returns to his village, but his best friend suspects something is terribly wrong.',
    longDescription: 'Yoshiki and Hikaru are two boys living in a small village. One day, Hikaru goes into the mountains and doesn\'t come back for a week. When he finally returns, he doesn\'t seem to remember anything. Yoshiki knows it\'s Hikaru, but he also feels that something is fundamentally different. When he confronts this "Hikaru," it admits to being something else, and makes him a promise to never harm him. A story of an unknown entity and the friend who accepts it.',
    genres: ['Horror', 'Mystery', 'Supernatural'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/the-summer-hikaru-died-1-285x399.webp?t=1689815205',
    imageHint: 'imposter friend',
    status: 'Trending',
    chapters: 40,
    releaseYear: 2021,
  },
  {
    id: 'phantom-whispers',
    title: 'Phantom Whispers',
    type: 'Manga',
    description: 'In a city of secrets, a detective hunts a ghost from his past.',
    longDescription: 'Detective Kaito is haunted by a case that went cold years ago. When a series of strange occurrences begin to plague the city, he realizes the phantom from his past has returned. He must now confront his own demons to unravel a conspiracy that threatens to consume everything he holds dear.',
    genres: ['Mystery', 'Supernatural', 'Psychological'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/phantom-whispers-1-285x399.webp?t=1729736174',
    imageHint: 'mystery phantom',
    status: 'Latest',
    chapters: 45,
    releaseYear: 2024,
  },
  {
    id: 'the-guy-she-was-interested-in-wasnt-a-guy-at-all',
    title: 'The Guy She Was Interested In Wasn\'t a Guy at All',
    type: 'Manga',
    description: 'A high school girl falls for a mysterious "prince" at a record store, who turns out to be her quiet female classmate.',
    longDescription: 'Aya Oosawa, a high school girl, can\'t stop thinking about the mysterious, deep-voiced "prince" she meets at a record store. She\'s shocked to discover this "prince" is actually her quiet and gloomy classmate, Mitsuki. A heartwarming story about a girl-girl romance that blossoms through a shared love of music.',
    genres: ['Romance', 'Slice of Life', 'School', 'Girls Love'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/the-guy-she-was-interested-in-wasnt-a-guy-at-all-1-285x399.webp?t=1724083780',
    imageHint: 'girl romance',
    status: 'Latest',
    chapters: 20,
    releaseYear: 2022,
  },
  {
    id: 'monster',
    title: 'Monster',
    type: 'Manga',
    description: 'A brilliant surgeon\'s life spirals into chaos after he chooses to save a young boy over a prominent politician.',
    longDescription: 'Dr. Kenzo Tenma, a brilliant Japanese neurosurgeon working in Germany, faces a moral dilemma: save a young boy or the city\'s mayor. His decision to save the boy, Johan, has unforeseen and catastrophic consequences that intertwine their lives in a horrifying web of mystery and murder. Tenma finds himself on the run, trying to stop the monster he helped create.',
    genres: ['Mystery', 'Thriller', 'Psychological', 'Drama'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/monster-1-285x409.webp?t=1715712943',
    imageHint: 'psychological thriller',
    status: 'Trending',
    chapters: 162,
    releaseYear: 1994,
  },
  {
    id: 'little-mushroom',
    title: 'Little Mushroom',
    type: 'Manga',
    description: 'An Anmo, a mushroom, has a mission to save his species.',
    longDescription: 'In the abyss, a sentient mushroom named An Anmo has a mission to save his species from extinction. He must venture into the dangerous human world to find a way to survive, all while hiding his true nature.',
    genres: ['Sci-Fi', 'Post-Apocalyptic', 'Drama'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/little-mushroom-1-285x399.webp?t=1755306938',
    imageHint: 'mushroom boy',
    status: 'Latest',
    chapters: 70,
    releaseYear: 2021,
  },
  {
    id: 'got-dropped-into-a-ghost-story-still-gotta-work-novel',
    title: 'Got Dropped Into a Ghost Story, Still Gotta Work (Novel)',
    type: 'Manga',
    description: 'An office worker is isekai\'d into a horror story and just wants to do his job.',
    longDescription: 'An ordinary office worker is suddenly transported into a ghost story. Surrounded by terrifying spirits and supernatural events, his main goal remains unchanged: he still has to go to work. A unique blend of horror and comedy as a salaryman tries to maintain his work-life balance in a haunted world.',
    genres: ['Comedy', 'Horror', 'Supernatural', 'Isekai'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/got-dropped-into-a-ghost-story-still-gotta-work-novel-1-285x399.webp?t=1730776149',
    imageHint: 'ghost story office',
    status: 'Latest',
    chapters: 50,
    releaseYear: 2022,
  },
  {
    id: 'daytime-star',
    title: 'Daytime Star',
    type: 'Manga',
    description: 'A story about a young woman who works at an aquarium and the mysterious man she meets.',
    longDescription: 'Yume works at an aquarium, finding solace in the quiet world of the sea creatures. Her peaceful life is interrupted by the appearance of a brooding, mysterious man who seems to carry a heavy burden. As they get to know each other, they find that they might be able to heal each other\'s wounds.',
    genres: ['Romance', 'Slice of Life', 'Drama'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/daytime-star-1-285x399.webp?t=1658082451',
    imageHint: 'aquarium romance',
    status: 'Latest',
    chapters: 40,
    releaseYear: 2021,
  },
  {
    id: 'a-home-far-away',
    title: 'A Home Far Away',
    type: 'Manga',
    description: 'A story about finding a new home and family in an unexpected place.',
    longDescription: 'After a family tragedy, a young girl is sent to live with distant relatives in a remote village. There, she discovers the meaning of home and belonging in the kindness of strangers and the beauty of the countryside.',
    genres: ['Slice of Life', 'Drama'],
    rating: 4.6,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/a-home-far-away-1-285x406.webp?t=1658737133',
    imageHint: 'distant home',
    status: 'Latest',
    chapters: 25,
    releaseYear: 2022,
  },
  {
    id: 'seasons-of-lovesome',
    title: 'Seasons of Lovesome',
    type: 'Manga',
    description: 'A romance that blossoms and changes through the four seasons.',
    longDescription: 'Follow the relationship of a young couple as their love story unfolds through the vibrant colors of spring, the warmth of summer, the melancholy of autumn, and the quiet intimacy of winter. Each season brings new challenges and joys, testing and strengthening their bond.',
    genres: ['Romance', 'Slice of Life'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/seasons-of-lovesome-1-285x399.webp?t=1723612841',
    imageHint: 'seasons love',
    status: 'Latest',
    chapters: 55,
    releaseYear: 2021,
  },
  {
    id: 'run-wild-novel',
    title: 'Run Wild (Novel)',
    type: 'Manga',
    description: 'In a world of werewolves, a young omega defies expectations and fights for his freedom.',
    longDescription: 'In a society governed by werewolf pack dynamics, an omega is expected to be submissive. But when a rebellious young omega refuses to accept his fate, he challenges the alpha and ignites a conflict that could tear their world apart. It is a story of breaking free from destiny and fighting for the right to choose your own path.',
    genres: ['Fantasy', 'Action', 'Supernatural'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/run-wild-novel-1-285x399.webp?t=1725941358',
    imageHint: 'werewolf action',
    status: 'Latest',
    chapters: 90,
    releaseYear: 2023,
  }
];

export const genres: GenreType[] = [
  {
    id: 'action',
    name: 'Action',
    description: 'High-octane series with intense fight scenes and thrilling sequences.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452301/lgi39qi7kmzdipemivm1_p9kewu.jpg',
    imageHint: 'action explosion',
  },
  {
    id: 'romance',
    name: 'Romance',
    description: 'Heartwarming stories centered around love and relationships.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452574/blue-box-and-horimiya_hxxsuo.avif',
    imageHint: 'romantic couple',
  },
  {
    id: 'sci-fi',
    name: 'Sci-Fi',
    description: 'Futuristic settings, advanced technology, and space exploration.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452482/Sci-fi-anime_qp7ers.webp',
    imageHint: 'sci-fi city',
  },
  {
    id: 'fantasy',
    name: 'Fantasy',
    description: 'Worlds of magic, mythical creatures, and epic quests.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1762452812/desktop-wallpaper-anime-boy-under-umbrella-with-black-coat-suit-dress-anime-boy_tw8cdi.jpg',
    imageHint: 'fantasy castle',
  },
  {
    id: 'comedy',
    name: 'Comedy',
    description: 'Lighthearted series designed to make you laugh.',
    imageUrl: 'https://res.cloudinary.com/doklib3it/image/upload/v1763280262/comedy-anime-series-ott_bhzgc1.jpg',
    imageHint: 'funny characters',
  },
  {
    id: 'drama',
    name: 'Drama',
    description: 'Emotionally charged narratives and character development.',
    imageUrl: findImage('genre-drama').url,
    imageHint: findImage('genre-drama').hint,
  },
];

export const fandomPosts: FandomPost[] = [
  {
    id: 1,
    author: 'AnimeFan_123',
    avatarUrl: findImage('avatar-1').url,
    avatarHint: findImage('avatar-1').hint,
    content: "Just finished Cyber Sentinel. The ending was absolutely mind-blowing! I can't believe they pulled that off. 10/10 masterpiece.",
    timestamp: '2 hours ago',
    sentiment: 'positive',
    sentimentScore: 0.9,
  },
  {
    id: 2,
    author: 'MechaMaster',
    avatarUrl: findImage('avatar-2').url,
    avatarHint: findImage('avatar-2').hint,
    content: 'The new episode of Iron-Clad Dynasty was okay, but the animation felt a bit off in the main fight scene. Anyone else notice that?',
    timestamp: '5 hours ago',
    sentiment: 'neutral',
    sentimentScore: -0.2,
  },
  {
    id: 3,
    author: 'ShojoLover',
    avatarUrl: findImage('avatar-3').url,
    avatarHint: findImage('avatar-3').hint,
    content: 'I really hated how they handled the main couple in Rooftop Confessions. It felt so forced and unnatural. Ruined the whole series for me.',
    timestamp: '1 day ago',
    sentiment: 'negative',
    sentimentScore: -0.8,
  },
];
