import type { MediaType, GenreType, FandomPost } from './types';
import { placeholderImages } from './placeholder-images.json';

const findImage = (id: string) => {
  const img = placeholderImages.find((p) => p.id === id);
  return {
    url: img?.imageUrl || 'https://picsum.photos/seed/placeholder/300/450',
    hint: img?.imageHint || 'placeholder',
  };
};

export const media: MediaType[] = [
  {
    id: 'cyber-sentinel',
    title: 'Cyber Sentinel',
    type: 'Anime',
    description: 'In a neon-drenched future, a lone android fights to protect humanity.',
    longDescription: 'In the year 2077, Neo-Kyoto is a sprawling metropolis of towering skyscrapers and shadowy alleys. Kaito, a state-of-the-art android known as a "Sentinel," uncovers a corporate conspiracy that threatens the very fabric of society. He must fight his way through rogue machines and augmented humans to expose the truth.',
    genres: ['Sci-Fi', 'Action', 'Cyberpunk'],
    rating: 4.8,
    imageUrl: findImage('anime-1').url,
    imageHint: findImage('anime-1').hint,
    status: 'Featured',
  },
  {
    id: 'chainsaw-man-reze-arc',
    title: 'Chainsaw Man: The Movie - Reze Arc',
    type: 'Anime',
    description: 'Denji falls for a new girl, Reze, who is not what she seems.',
    longDescription: 'Denji meets Reze, a girl who is seemingly his perfect match. But their budding romance is tragically cut short when it is revealed that Reze is the Bomb Devil, sent to steal the Chainsaw Man\'s heart. A heart-wrenching battle ensues, testing Denji\'s resolve and his very humanity.',
    genres: ['Action', 'Supernatural', 'Horror'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/chainsaw-man-the-movie-reze-arc-1-285x399.webp?t=1750358534',
    imageHint: 'chainsaw man reze',
    status: 'Trending',
  },
  {
    id: 'the-apothecary-diaries-2nd-season',
    title: 'The Apothecary Diaries 2nd Season',
    type: 'Anime',
    description: 'Maomao solves more medical mysteries in the imperial court.',
    longDescription: 'The clever and cynical Maomao continues her life as a palace apothecary. With her extensive knowledge of medicine and poisons, she once again finds herself entangled in the complex and often dangerous affairs of the imperial inner court, solving medical mysteries that baffle everyone else.',
    genres: ['Mystery', 'Historical', 'Drama'],
    rating: 4.9,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-apothecary-diaries-2nd-season-1-285x403.webp?t=1729603194',
    imageHint: 'apothecary maomao',
    status: 'Trending',
  },
  {
    id: 'muzik-tiger-in-the-forest-2nd-season',
    title: 'MUZIK TIGER In the Forest 2nd Season',
    type: 'Anime',
    description: 'The adorable tiger and his friends continue their fun adventures in the forest.',
    longDescription: 'Join MUZIK TIGER and his delightful friends for another season of heartwarming adventures! From discovering hidden clearings to meeting new forest dwellers, their journey is filled with laughter, friendship, and the simple joys of nature.',
    genres: ['Slice of Life', 'Comedy', 'Kids'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/images/anime/default/default-anime-fall.png',
    imageHint: 'cute tiger',
    status: 'Latest',
  },
  {
    id: 'may-i-ask-for-one-final-thing',
    title: 'May I Ask For One Final Thing?',
    type: 'Anime',
    description: 'A scorned noblewoman unleashes her fury upon those who betrayed her.',
    longDescription: 'Scarlett, a noblewoman whose engagement was suddenly annulled, is falsely accused and thrown into prison. When she\'s pushed to her limit, she decides to stop holding back. "May I ask for one final thing?" she says, before unleashing her true, violent nature upon her tormentors. This is a story of brutal, satisfying revenge.',
    genres: ['Action', 'Fantasy', 'Romance'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/may-i-ask-for-one-final-thing-1-285x427.webp?t=1744408497',
    imageHint: 'furious noblewoman',
    status: 'Trending',
  },
  {
    id: 'galactic-wanderers',
    title: 'Galactic Wanderers',
    type: 'Anime',
    description: 'The crew of a small spaceship explores unknown corners of the galaxy.',
    longDescription: 'The starship "Odyssey" and its ragtag crew journey through uncharted space, encountering strange new worlds, ancient alien artifacts, and dangerous cosmic phenomena. Each episode is a new adventure, a new mystery to solve in the vastness of the galaxy.',
    genres: ['Sci-Fi', 'Adventure', 'Space Opera'],
    rating: 4.4,
    imageUrl: findImage('anime-6').url,
    imageHint: findImage('anime-6').hint,
    status: 'Latest',
  },
  {
    id: 'the-banished-court-magician-aims-to-become-the-strongest',
    title: 'The Banished Court Magician Aims to Become the Strongest',
    type: 'Anime',
    description: 'A talented magician, banished from court, seeks to become the strongest of all.',
    longDescription: 'Betrayed and exiled from the royal court he served, a prodigious magician now wanders the lands. To protect those he cares for and to prove his worth, he embarks on a solitary journey to hone his skills and surpass every magical limit, aiming to become the undisputed strongest magician in the world.',
    genres: ['Fantasy', 'Adventure', 'Action'],
    rating: 4.8,
    imageUrl: 'https://cdn.anime-planet.com/anime/primary/the-banished-court-magician-aims-to-become-the-strongest-1-285x399.webp?t=1759618348',
    imageHint: 'court magician',
    status: 'Trending',
  },
  {
    id: 'i-became-a-patron-of-villains',
    title: 'I Became a Patron of Villains',
    type: 'Manga',
    description: 'A woman is reincarnated into a novel to become a patron for the villains she once pitied.',
    longDescription: 'Waking up in the world of her favorite novel, a character decides she\'s had enough of the tragic fates of its villains. Instead of following the plot, she uses her knowledge to become their secret supporter, guiding them away from their dark destinies while trying to survive in a world where her actions could have unforeseen consequences.',
    genres: ['Fantasy', 'Isekai', 'Drama'],
    rating: 4.7,
    imageUrl: 'https://cdn.anime-planet.com/manga/primary/i-became-a-patron-of-villains-1-285x399.webp?t=1761280414',
    imageHint: 'patron of villains',
    status: 'Trending',
  },
  {
    id: 'master-chefs-table',
    title: 'Master Chef\'s Table',
    type: 'Manga',
    description: 'A young chef aims to become the best in the world.',
    longDescription: 'Sora inherited his family\'s small diner, but he dreams of winning the world\'s most prestigious culinary competition. He must innovate and create dishes that can impress a panel of god-tier chefs.',
    genres: ['Cooking', 'Slice of Life'],
    rating: 4.5,
    imageUrl: findImage('manga-3').url,
    imageHint: findImage('manga-3').hint,
    status: 'Latest',
  },
  {
    id: 'dust-and-ruin',
    title: 'Dust and Ruin',
    type: 'Manga',
    description: 'A survivor navigates a desolate, post-apocalyptic world.',
    longDescription: 'Years after "The Calamity" turned the world into a desert wasteland, a lone scavenger named Jin travels from ruin to ruin, searching for a rumored oasis. He faces mutated beasts, desperate raiders, and the ghosts of the past.',
    genres: ['Post-Apocalyptic', 'Sci-Fi', 'Action'],
    rating: 4.3,
    imageUrl: findImage('manga-6').url,
    imageHint: findImage('manga-6').hint,
    status: 'Latest',
  },
];

export const genres: GenreType[] = [
  {
    id: 'action',
    name: 'Action',
    description: 'High-octane series with intense fight scenes and thrilling sequences.',
    imageUrl: findImage('genre-action').url,
    imageHint: findImage('genre-action').hint,
  },
  {
    id: 'romance',
    name: 'Romance',
    description: 'Heartwarming stories centered around love and relationships.',
    imageUrl: findImage('genre-romance').url,
    imageHint: findImage('genre-romance').hint,
  },
  {
    id: 'sci-fi',
    name: 'Sci-Fi',
    description: 'Futuristic settings, advanced technology, and space exploration.',
    imageUrl: findImage('genre-scifi').url,
    imageHint: findImage('genre-scifi').hint,
  },
  {
    id: 'fantasy',
    name: 'Fantasy',
    description: 'Worlds of magic, mythical creatures, and epic quests.',
    imageUrl: findImage('genre-fantasy').url,
    imageHint: findImage('genre-fantasy').hint,
  },
  {
    id: 'slice-of-life',
    name: 'Slice of Life',
    description: 'Realistic depictions of everyday life and experiences.',
    imageUrl: findImage('genre-slice-of-life').url,
    imageHint: findImage('genre-slice-of-life').hint,
  },
  {
    id: 'comedy',
    name: 'Comedy',
    description: 'Lighthearted series designed to make you laugh.',
    imageUrl: findImage('genre-comedy').url,
    imageHint: findImage('genre-comedy').hint,
  },
];

export const fandomPosts: FandomPost[] = [
  {
    id: 1,
    author: 'AnimeFan_123',
    avatarUrl: findImage('avatar-1').url,
    avatarHint: findImage('avatar-1').hint,
    content: "Just finished Cyber Sentinel. The ending was absolutely mind-blowing! I can't believe they pulled that off. 10/10 masterpiece.",
    timestamp: '2 hours ago',
    sentiment: 'positive',
    sentimentScore: 0.9,
  },
  {
    id: 2,
    author: 'MechaMaster',
    avatarUrl: findImage('avatar-2').url,
    avatarHint: findImage('avatar-2').hint,
    content: 'The new episode of Iron-Clad Dynasty was okay, but the animation felt a bit off in the main fight scene. Anyone else notice that?',
    timestamp: '5 hours ago',
    sentiment: 'neutral',
    sentimentScore: -0.2,
  },
  {
    id: 3,
    author: 'ShojoLover',
    avatarUrl: findImage('avatar-3').url,
    avatarHint: findImage('avatar-3').hint,
    content: 'I really hated how they handled the main couple in Rooftop Confessions. It felt so forced and unnatural. Ruined the whole series for me.',
    timestamp: '1 day ago',
    sentiment: 'negative',
    sentimentScore: -0.8,
  },
];
