// ------------------------------------------------------------------
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// ------------------------------------------------------------------

// This configuration is designed to work with Vercel and other hosting providers.
// It uses NEXT_PUBLIC_ environment variables to securely load the Firebase configuration.

export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};
